pipeline {
    agent any

    environment {
        AWS_REGION = "ap-south-1"
        AWS_ACCOUNT_ID = "406460435005"

        FRONTEND_REPO = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/frontend"
        BACKEND_REPO  = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/backend"
    }

    stages {

        stage('Checkout Source') {
            steps {
                checkout scm
            }
        }

        stage('Login to Amazon ECR') {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-creds'
                ]]) {
                    sh '''
                    aws ecr get-login-password --region ${AWS_REGION} | \
                    docker login --username AWS --password-stdin \
                    ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
                    '''
                }
            }
        }

        stage('Build Docker Images') {
            steps {
                sh '''
                docker build -t frontend:latest ./app/frontend
                docker build -t backend:latest ./app/backend

                docker tag frontend:latest ${FRONTEND_REPO}:latest
                docker tag backend:latest ${BACKEND_REPO}:latest
                '''
            }
        }

        stage('Push Images to ECR') {
            steps {
                sh '''
                docker push ${FRONTEND_REPO}:latest
                docker push ${BACKEND_REPO}:latest
                '''
            }
        }

        stage('Deploy to Amazon EKS') {
            steps {
                sh '''
                kubectl rollout restart deployment/frontend
                kubectl rollout restart deployment/backend
                '''
            }
        }

        stage('Verify Deployment') {
            steps {
                sh '''
                kubectl rollout status deployment/frontend
                kubectl rollout status deployment/backend

                kubectl get pods
                kubectl get svc
                kubectl get ingress
                '''
            }
        }
    }

    post {

        success {
            echo "Application deployed successfully to Amazon EKS."
        }

        failure {
            echo "Pipeline failed. Check the Jenkins console output."
        }

        always {
            sh '''
            docker image prune -f
            '''
        }
    }
}
